In [1]:
import numpy as np

A = np.array([[1, 0, -1, 2], [2, 1, -1, 5], [3, 3, 0, 9]])
b = np.array([1, 4, 9])

In [2]:
# Part a

#Since x_3 and x_4 are free variables, we will assign them random numbers with numpy.random
x_3 = np.random.random()
x_4 = np.random.random()

x_n = np.array([x_3 - 2*x_4, -x_3 - x_4, x_3, x_4])
print('Solution for Ax = 0')
print(x_n)
print('\n')
result = np.around(A.dot(x_n),6)
print('Confirming that Ax = 0')
print(result)

Solution for Ax = 0
[-0.24602768 -0.83691914  0.47593687  0.36098227]


Confirming that Ax = 0
[0. 0. 0.]


In [3]:
# Part b

#Since x_3 and x_4 are free variables, we will write solution set in terms of them. And since we are looking for
# a particular solution, assigning x_3 and x_4 as 0 will make x_p = [1 2 0 0]^T. Then check whether A.x_p = b where
# b is [1 4 9]^T
x_3 = 0
x_4 = 0

print('Solution for Ax = b')
x_p = np.array([ 1 + x_3 - 2*x_4, 2 -x_3 - x_4, x_3, x_4])
print(x_p)
print('\n')
print('Confirming that Ax = b')
result = A.dot(x_p)
print(result)

Solution for Ax = b
[1 2 0 0]


Confirming that Ax = b
[1 4 9]


In [4]:
# Part c

x_3 = np.random.random()
x_4 = np.random.random()

x_c = np.array([ 1 + x_3 - 2*x_4, 2 -x_3 - x_4, x_3, x_4])

print('Confirming that Ax = b')
result = A.dot(x_c)
print(result)

Confirming that Ax = b
[1. 4. 9.]


In [5]:
# Part d 

u, s, v = np.linalg.svd(A)

# Make sigma in the correct form which is 3x4 matrix
sigma = np.zeros((3,4))
for i in range(len(sigma[:,0])):
    for j in range(len(sigma[0])):
        if( i == j ):
            # Instead of zero, it assigns third sigma value as 2*10^-16, which makes problem when taking reciprocal.
            # To resolve that issue, i have just assigned 0 instead 2*10^-16
            if(s[i] > 10 **-15):
                sigma[i,j] = s[i]
            else:
                sigma[i,j] = 0
                
            
# To find sigma_plus, take reciprocals of the non-zero values.
sigma_plus = np.zeros((3,4))
for i in range(len(sigma[:,0])):
    for j in range(len(sigma[0])):
         if( i == j and sigma[i,j] != 0):
            sigma_plus[i,j] = 1/sigma[i,j]

print('U is:')
print(u)
print('V is:')
print(v)
print('sigma is:')
print(sigma)

U is:
[[-0.1898465   0.70019575 -0.6882472 ]
 [-0.47607011  0.54742401  0.6882472 ]
 [-0.85867081 -0.45831524 -0.22941573]]
V is:
[[-0.32168832 -0.26407196  0.05761637 -0.90744861]
 [ 0.27016145 -0.53217213 -0.80233358  0.00815077]
 [ 0.89002517  0.22009547  0.14994474 -0.37004021]
 [ 0.17715703 -0.77370331  0.57485455  0.19884876]]
sigma is:
[[11.55776837  0.          0.          0.        ]
 [ 0.          1.55498883  0.          0.        ]
 [ 0.          0.          0.          0.        ]]


In [6]:
A_pseudo = (v.T).dot(sigma_plus.T).dot(u.T)
print('Pseudo inverse of A by SVD decomposition :')
print(A_pseudo)
print('\n')
print('To see how accurate our pseudo inverse of A, is we check A.A_pseudo.A = A')
print(A.dot(A_pseudo).dot(A))

# Finally, find pseudo inverse of A with numpy.linalg.pinv(A)
A_pseudo_2 = np.linalg.pinv(A)
print('\n')
print('Pseudo inverse of A with numpy.linalg.pinv(A)')
print(A_pseudo_2)

Pseudo inverse of A by SVD decomposition :
[[ 0.12693498  0.10835913 -0.05572755]
 [-0.23529412 -0.17647059  0.17647059]
 [-0.3622291  -0.28482972  0.23219814]
 [ 0.01857585  0.04024768  0.06501548]]


To see how accurate our pseudo inverse of A, is we check A.A_pseudo.A = A
[[ 1.00000000e+00 -1.66533454e-16 -1.00000000e+00  2.00000000e+00]
 [ 2.00000000e+00  1.00000000e+00 -1.00000000e+00  5.00000000e+00]
 [ 3.00000000e+00  3.00000000e+00  1.66533454e-16  9.00000000e+00]]


Pseudo inverse of A with numpy.linalg.pinv(A)
[[ 0.12693498  0.10835913 -0.05572755]
 [-0.23529412 -0.17647059  0.17647059]
 [-0.3622291  -0.28482972  0.23219814]
 [ 0.01857585  0.04024768  0.06501548]]


In [7]:
# Part e

# 1. Set free variables to zero
x_3 = 0
x_4 = 0
x_sparsest = np.array([ 1 + x_3 - 2*x_4, 2 -x_3 - x_4, x_3, x_4])

print('Sparsest solution example for x is')
print(x_sparsest)

# 2. Set one of the free variables to zero. And set other free variable such that one of the pivots become 0.
x_3 = 0
x_4 = 1/2
x_sparsest = np.array([ 1 + x_3 - 2*x_4, 2 -x_3 - x_4, x_3, x_4])

print('Sparsest solution example for x is')
print(x_sparsest)

# 3.Set free variables such that both pivots are zero.
x_3 = 1
x_4 = 1
x_sparsest = np.array([ 1 + x_3 - 2*x_4, 2 -x_3 - x_4, x_3, x_4])

print('Sparsest solution example for x is')
print(x_sparsest)

Sparsest solution example for x is
[1 2 0 0]
Sparsest solution example for x is
[0.  1.5 0.  0.5]
Sparsest solution example for x is
[0 0 1 1]


In [8]:
# Part f

L2 = A_pseudo.dot(b)
print('Least norm solution is:')
print(L2)

Least norm solution is:
[0.05882353 0.64705882 0.58823529 0.76470588]
